// Generated by CoffeeScript 1.12.7
(function() {
  this.TemplateController = (function() {
    function TemplateController() {}

    TemplateController.prototype.statics = function() {};

    $.get('http://localhost:8080/statics', function(data) {
      var context, html;
      context = {
        registers: data.registers.reverse(),
        counter: data.registers.length,
        message: data.message
      };
      html = ViewResolver.mergeViewWithModel("#statics", context);
      $("#handlebars").html(html);
      return new Chartist.Line('.chart', {
        labels: [1, 2, 3, 4, 5, 6, 7, 8],
        series: [[5, 9, 7, 8, 5, 3, 5, 4]]
      }, {
        low: 0,
        showArea: true
      });
    });

    TemplateController.prototype.assaults = function() {
      var html;
      console.log("Entrando a ver los asaltos");
      html = ViewResolver.mergeViewWithModel("#assaults");
      return $("#handlebars").html(html);
    };

    TemplateController.prototype.register = function() {
      var html;
      html = ViewResolver.mergeViewWithModel("#register");
      $("#handlebars").html(html);
      return Validator.validateNewForm();
    };

    return TemplateController;

  })();

  this.ApiController = (function() {
    function ApiController() {}

    ApiController.add = function() {
      return $.ajax({
        url: 'http://localhost:8080/newRegister',
        type: 'post',
        data: $('#registerForm').serialize(),
        success: function() {}
      }, console.log("Registro agregado"), {
        error: function() {
          return console.log("Error al agregar");
        }
      });
    };

    return ApiController;

  })();

}).call(this);
