// Generated by CoffeeScript 1.12.7
(function() {
  this.TemplateController = (function() {
    function TemplateController() {}

    TemplateController.prototype.statics = function() {
      var html;
      console.log("Estadisticas route");
      html = ViewResolver.mergeViewWithModel("#statics");
      return $("#handlebars").html(html);
    };

    TemplateController.prototype.register = function() {
      var html;
      console.log("Rgister route");
      html = ViewResolver.mergeViewWithModel("#register");
      return $("#handlebars").html(html);
    };

    return TemplateController;

  })();

}).call(this);
