// Generated by CoffeeScript 1.12.7
(function() {
  this.ViewResolver = (function() {
    function ViewResolver() {}

    ViewResolver.mergeViewWithModel = function(templateName, model) {
      var source, template;
      source = $(templateName).html();
      template = Handlebars.compile(source);
      return template(model);
    };

    return ViewResolver;

  })();

  this.Validator = (function() {
    function Validator() {}

    Validator.validateNewForm = function() {
      return $('#submitRegister').click(function() {
        console.log("Click para registro");
        return ApiController.add();
      });
    };

    return Validator;

  })();

}).call(this);
