// Generated by CoffeeScript 1.12.7
(function() {
  this.ViewResolver = (function() {
    function ViewResolver() {}

    ViewResolver.mergeViewWithModel = function(templateName, model) {
      var source, template;
      source = $(templateName).html();
      template = Handlebars.compile(source);
      return template(model);
    };

    return ViewResolver;

  })();

}).call(this);
